name: 🔎 Checking pull request

on:
    pull_request:

jobs:
    run-tests:
        name: 🔎 Run the test suite
        uses: ./.github/workflows/phpunit_tests.yml
    static-analysis:
        name: 🔎 Analyse the code for errors
        uses: ./.github/workflows/phpstan_analysis.yml
